/**
 * Generated by `createschema user.ForgotPassword 'user:Relationship:User:CASCADE; token:Text; requestedAt:DateTimeUtc; expiresAt:DateTimeUtc; usedAt:DateTimeUtc;' --force`
 */

async function canReadForgotPasswords ({ authentication: { item: user } }) {
    if (!user) return false
    if (user.isAdmin) return {}
    return {
        // TODO(codegen): write canReadForgotPasswords logic!
    }
}

async function canManageForgotPasswords ({ authentication: { item: user }, originalInput, operation, itemId }) {
    if (!user) return false
    if (user.isAdmin) return true
    if (operation === 'create') {
        // TODO(codegen): write canManageForgotPasswords create logic!
        return true
    } else if (operation === 'update') {
        // TODO(codegen): write canManageForgotPasswords update logic!
        return true
    }
    return false
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadForgotPasswords,
    canManageForgotPasswords,
}
